"""Add AdmissionLetter model

Revision ID: 126d19b97ef0
Revises: 584f23d2cd4c
Create Date: 2025-07-12 22:07:46.601868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126d19b97ef0'
down_revision = '584f23d2cd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('previous_school', sa.String(length=150), nullable=True),
    sa.Column('student_class', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_letter')
    # ### end Alembic commands ###
