"""Add notes model

Revision ID: 51487abe0a71
Revises: 2427dee9f768
Create Date: 2025-07-12 23:33:29.441249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51487abe0a71'
down_revision = '2427dee9f768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('student_class', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
